### ISSUE TITLE
Launcher doesn't find can't find eldenring.exe, or the original start_protected_game.exe

### ISSUE THREAD

**Issue by glaburrrg** [v-maxson/EldenRingLauncher#1]
well everything is in the title, the launcher doesn't seem to be able to find any file (or just the to executable mentionned...)

But in steam the game is marked as launched

**Comment by v-maxson** [comment]
Try launching it as Administrator and see if that fixes this issue.

Steam would be marking the game as launched because it is instead launching this utility. 

So sorry for the late reply!
